//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

public partial class TicketEntities : DbContext
{
    public TicketEntities()
        : base("name=TicketEntities")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public virtual DbSet<BlockList> BlockLists { get; set; }
    public virtual DbSet<Client> Clients { get; set; }
    public virtual DbSet<Staff> Staffs { get; set; }
    public virtual DbSet<Ticket_Activity> Ticket_Activity { get; set; }
    public virtual DbSet<Ticket_Collaborator> Ticket_Collaborator { get; set; }
    public virtual DbSet<Ticket_Master> Ticket_Master { get; set; }
}
