//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class BlockList
{
    public int BlockListID { get; set; }
    public string Email { get; set; }
}

public partial class Client
{
    public int Client_ID { get; set; }
    public string FullName { get; set; }
    public string Gender { get; set; }
    public string Email { get; set; }
    public string Password { get; set; }
    public string StreetAddress1 { get; set; }
    public string StreetAddress2 { get; set; }
    public string City { get; set; }
    public string State { get; set; }
    public string Country { get; set; }
    public string Zip { get; set; }
}

public partial class Staff
{
    public int Staff_ID { get; set; }
    public string Username { get; set; }
    public string Password { get; set; }
    public bool IsActive { get; set; }
}

public partial class Ticket_Activity
{
    public int ActivityID { get; set; }
    public int TicketID { get; set; }
    public string ActivityType { get; set; }
    public string Summary { get; set; }
    public string Description { get; set; }
    public System.DateTime ActivityDate { get; set; }
    public Nullable<int> ActedBy { get; set; }
    public string ActorName { get; set; }
    public Nullable<bool> Unread { get; set; }

    public virtual Ticket_Master Ticket_Master { get; set; }
}

public partial class Ticket_Collaborator
{
    public int CollaboratorID { get; set; }
    public int TicketID { get; set; }
    public string Email { get; set; }
    public string FullName { get; set; }
    public string FieldType { get; set; }

    public virtual Ticket_Master Ticket_Master { get; set; }
}

public partial class Ticket_Master
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Ticket_Master()
    {
        this.Ticket_Activity = new HashSet<Ticket_Activity>();
        this.Ticket_Collaborator = new HashSet<Ticket_Collaborator>();
    }

    public int TicketID { get; set; }
    public string Email { get; set; }
    public string FullName { get; set; }
    public Nullable<int> CreatedBy { get; set; }
    public System.DateTime CreationDate { get; set; }
    public string TicketSource { get; set; }
    public string Category { get; set; }
    public string Subject { get; set; }
    public Nullable<int> AssignTo { get; set; }
    public string TicketStatus { get; set; }
    public Nullable<byte> Priority { get; set; }
    public Nullable<int> ClosedBy { get; set; }
    public Nullable<System.DateTime> ClosedDate { get; set; }
    public bool IsDeleted { get; set; }
    public bool AcknowledgementSent { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Ticket_Activity> Ticket_Activity { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Ticket_Collaborator> Ticket_Collaborator { get; set; }
}
