//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MailWindowsService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket_Master
    {
        public Ticket_Master()
        {
            this.Ticket_Activity = new HashSet<Ticket_Activity>();
            this.Ticket_Collaborator = new HashSet<Ticket_Collaborator>();
        }
    
        public int TicketID { get; set; }
        public string Email { get; set; }
        public string FullName { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public System.DateTime CreationDate { get; set; }
        public string TicketSource { get; set; }
        public string Category { get; set; }
        public string Subject { get; set; }
        public Nullable<int> AssignTo { get; set; }
        public string TicketStatus { get; set; }
        public Nullable<byte> Priority { get; set; }
        public Nullable<int> ClosedBy { get; set; }
        public Nullable<System.DateTime> ClosedDate { get; set; }
        public bool IsDeleted { get; set; }
        public bool AcknowledgementSent { get; set; }
    
        public virtual ICollection<Ticket_Activity> Ticket_Activity { get; set; }
        public virtual ICollection<Ticket_Collaborator> Ticket_Collaborator { get; set; }
    }
}
