//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MailWindowsService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket_Collaborator
    {
        public int CollaboratorID { get; set; }
        public int TicketID { get; set; }
        public string Email { get; set; }
        public string FullName { get; set; }
        public string FieldType { get; set; }
    
        public virtual Ticket_Master Ticket_Master { get; set; }
    }
}
