//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MailWindowsService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket_Activity
    {
        public int ActivityID { get; set; }
        public int TicketID { get; set; }
        public string ActivityType { get; set; }
        public string Summary { get; set; }
        public string Description { get; set; }
        public System.DateTime ActivityDate { get; set; }
        public Nullable<int> ActedBy { get; set; }
        public string ActorName { get; set; }
        public Nullable<bool> Unread { get; set; }
    
        public virtual Ticket_Master Ticket_Master { get; set; }
    }
}
